# These are supported funding model platforms

# GitHub Sponsors
github: [Refferq]

# Open Collective
# open_collective: refferq

# Patreon
# patreon: refferq

# Ko-fi
ko_fi: I3I31MM8N2

# Buy Me a Coffee
# buy_me_a_coffee: refferq

# Custom URLs (up to 4)
# custom: ['https://refferq.com/donate', 'https://paypal.me/refferq']
