"use client";
import { FormEvent, useState } from "react";

export default function RegisterPage(){
  const [step,setStep]=useState<"form"|"otp"|"done">("form"); const [message,setMessage]=useState("");
  const [form,setForm]=useState({name:"",email:"",password:"",referralCode:""}); const [code,setCode]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setMessage("");const res=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok){setMessage(data.error||"Не удалось создать заявку");return;}await fetch("/api/auth/send-otp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.email})});setStep("otp");}
  async function verify(e:FormEvent){e.preventDefault();const res=await fetch("/api/auth/verify-otp",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.email,code})});const data=await res.json();if(!res.ok){setMessage(data.error||"Неверный код");return;}setStep("done");}
  return <main className="auth-page"><section className="auth-card wide"><a className="brand auth-brand" href="/"><span className="brand-mark">S</span><span><b>Syntolk</b><small>Partners</small></span></a>
    {step==="form"&&<><p className="eyebrow">СТАТЬ ПАРТНЁРОМ</p><h1>Заявка в Syntolk Partners</h1><p className="muted">Для блогеров, фрилансеров, агентств и экспертов. Базовая комиссия — 20%.</p><form className="auth-form" onSubmit={submit}><label>Имя / название<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email<input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Пароль<input className="input" type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><small className="muted">Минимум 10 символов</small></label><label>Желаемый referral code <span className="muted">(необязательно)</span><input className="input" placeholder="ivan-blog" value={form.referralCode} onChange={e=>setForm({...form,referralCode:e.target.value})}/></label><button className="button primary" type="submit">Создать заявку</button></form></>}
    {step==="otp"&&<><p className="eyebrow">ПОДТВЕРЖДЕНИЕ EMAIL</p><h1>Введите код</h1><p className="muted">Мы отправили 6-значный код на {form.email}.</p><form className="auth-form" onSubmit={verify}><input className="input otp-input" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/><button className="button primary">Подтвердить email</button></form></>}
    {step==="done"&&<><p className="eyebrow">ГОТОВО</p><h1>Заявка создана</h1><p className="lead">Email подтверждён. Теперь заявка ожидает одобрения администратором Syntolk. В кабинет можно войти уже сейчас и увидеть статус.</p><a className="button primary" href="/partner">Открыть кабинет</a></>}
    {message&&<p className="form-message">{message}</p>}<p className="auth-footer">Уже зарегистрированы? <a href="/login">Войти</a></p>
  </section></main>;
}
